# Generated by Django 4.0 on 2022-01-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SafePassword.application')),
            ],
        ),
    ]
